# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y

#Battery Reporting
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Enable USB HID (Required for USB connection)
CONFIG_ZMK_USB=y

CONFIG_ZMK_STUDIO_LOCKING=n

# Enable Bluetooth
CONFIG_BT=y
CONFIG_ZMK_BLE=y

# Set the maximum number of paired devices (nice_view expects this)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# Enable the display
CONFIG_ZMK_DISPLAY=y
